from .algo_based_on_backward_movement import MemLeakDetectionAlgorithm
from .algo_based_on_poly_fit import MemLeakDetectionAlgorithmPolyFit
from .algo_based_on_change_points import MemLeakDetectionAlgorithmChangePoints
from .precog_change import Precog
from .precog_change_online import PrecogOnline